name: photoboom
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6

  image_picker: ^1.1.2      # Actualizado a la última versión para móviles
  file_picker: ^10.0.0      # Para seleccionar archivos desde el escritorio
  camera: ^0.11.0+1
  english_words: ^4.0.0
  provider: ^6.1.5
  firebase_auth: ^5.5.4
  firebase_ui_auth: ^1.16.1
  permission_handler: ^12.0.0+1
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: KaushanScript
      fonts:
        - asset: assets/fonts/KaushanScript-Regular.ttf


  assets:
    - assets/images/imagen1.jpg
    - assets/images/imagen2.jpg
    - assets/images/imagen3.jpg
    - assets/images/imagen4.jpg
