name: photoboom
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  firebase_auth: ^5.5.4
  firebase_ui_auth: ^1.16.1

  # Multimedia
  image_picker: ^1.1.2       # Móviles
  file_picker: ^10.0.0       # Escritorio
  camera: ^0.10.0+4

  # UI y utilidades
  english_words: ^4.0.0
  provider: ^6.1.5
  permission_handler: ^10.2.0
  flutter_staggered_grid_view: ^0.6.2

  # Base de datos local
  sqflite: ^2.3.2
  path: ^1.9.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/img/categoriasimg/
    - assets/images/imagen1.jpg
    - assets/images/imagen2.jpg
    - assets/images/imagen3.jpg
    - assets/images/imagen4.jpg

  fonts:
    - family: KaushanScript
      fonts:
        - asset: assets/fonts/KaushanScript-Regular.ttf
