// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSLvImAOp6FNIsZK5MPHhHJd_vVQjGNPc',
    appId: '1:682403335606:web:c573629cd7b19fef840517',
    messagingSenderId: '682403335606',
    projectId: 'photoboom-2fe50',
    authDomain: 'photoboom-2fe50.firebaseapp.com',
    storageBucket: 'photoboom-2fe50.firebasestorage.app',
    measurementId: 'G-16V41KRSWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD78yfCMCT6eLnvsNqeAI95PDdCejFMtw',
    appId: '1:682403335606:android:93ffc17966876d37840517',
    messagingSenderId: '682403335606',
    projectId: 'photoboom-2fe50',
    storageBucket: 'photoboom-2fe50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfTl9kDp8qQYGPJ9BI_ESkIAkPub7tQM8',
    appId: '1:682403335606:ios:8116be0b5234fb3b840517',
    messagingSenderId: '682403335606',
    projectId: 'photoboom-2fe50',
    storageBucket: 'photoboom-2fe50.firebasestorage.app',
    iosBundleId: 'com.example.photoboom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfTl9kDp8qQYGPJ9BI_ESkIAkPub7tQM8',
    appId: '1:682403335606:ios:8116be0b5234fb3b840517',
    messagingSenderId: '682403335606',
    projectId: 'photoboom-2fe50',
    storageBucket: 'photoboom-2fe50.firebasestorage.app',
    iosBundleId: 'com.example.photoboom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSLvImAOp6FNIsZK5MPHhHJd_vVQjGNPc',
    appId: '1:682403335606:web:547fe145902f4050840517',
    messagingSenderId: '682403335606',
    projectId: 'photoboom-2fe50',
    authDomain: 'photoboom-2fe50.firebaseapp.com',
    storageBucket: 'photoboom-2fe50.firebasestorage.app',
    measurementId: 'G-KVKYTEE97M',
  );
}
